server {
    listen 80 default_server;
    listen [::]:80 default_server;

    listen 443 ssl;
    listen [::]:443 ssl;

    server_name web.lab.test;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    ssl_certificate /etc/ssl/web.lab.test/certs/web.lab.test.crt;
    ssl_certificate_key /etc/ssl/web.lab.test/private/web.lab.test.key;

    location / {
        try_files $uri $uri/ =404;
    }
}